server:
  port: 8002
spring:
  application:
    name: scs-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    preferIpAddress: true
    instanceId:  ${spring.cloud.client.ip-address}:${server.port}
