server:
  port: 8002
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8001/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: scs-admin