spring:
  datasource:
    name: actDatasource
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #driver: com.mysql.jdbc.Driver
      driver-class-name: org.postgresql.Driver
      #基本属性
      url: jdbc:postgresql://192.168.152.131:5432/act
      username: psql
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 0
      max-open-prepared-statements: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
