server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: scs-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: baidu
          uri: https://www.baidu.com/
          predicates:
            - Path=/baidu
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/scs
    username: sa
    password: 6789@jkl
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: select version()
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 配置开启自动更新表结构
          auto: update