server:
  port: 8002
spring:
  application:
    name: scs-base
  cloud:
    nacos:
      config:
        shared-configs:
          - data-id: base.yml
            group: scs
            refresh: false